---
- name: Ensure that Apache is installed
  apt:
    name: apache2
    state: latest

- name: Start Apache Services
  service:
    name: ufw
    enabled: yes
    state: started

- name: Deploy configuration File
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/conf-available/apache2.conf.j2
  notify:
    - Restart Apache

- name: Copy site files
  template:
    src: /ui/quotes-ui/index.html
    dest: "{{ doc_root }}/index.html"

- name: Stop IPtables
  service:
    name: ufw
    state: stopped
